// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Datos.Modelos
{
    public partial class GruposEntidades
    {
        public GruposEntidades()
        {
            Entidades = new HashSet<Entidades>();
            TiposEntidades = new HashSet<TiposEntidades>();
        }

        [Key]
        public int IdGrupoEntidad { get; set; }
        [Required]
        [StringLength(120)]
        public string Descripcion { get; set; }
        [StringLength(1)]
        public string Comentario { get; set; }
        [StringLength(10)]
        public string Status { get; set; }
        public string NoEliminable { get; set; }
        [Column(TypeName = "date")]
        public DateTime? FechaRegistro { get; set; }

        [InverseProperty("IdGrupoEntidadNavigation")]
        public virtual ICollection<Entidades> Entidades { get; set; }
        [InverseProperty("IdGrupoEntidadNavigation")]
        public virtual ICollection<TiposEntidades> TiposEntidades { get; set; }
    }
}